// flow-typed signature: d44c5ee5f00b5b9b929a373f57d1e1a1
// flow-typed version: <<STUB>>/babel-preset-gatsby_v0.5.2/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-gatsby'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-gatsby' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-preset-gatsby/dependencies' {
  declare module.exports: any;
}

declare module 'babel-preset-gatsby/optimize-hook-destructuring' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-preset-gatsby/dependencies.js' {
  declare module.exports: $Exports<'babel-preset-gatsby/dependencies'>;
}
declare module 'babel-preset-gatsby/index' {
  declare module.exports: $Exports<'babel-preset-gatsby'>;
}
declare module 'babel-preset-gatsby/index.js' {
  declare module.exports: $Exports<'babel-preset-gatsby'>;
}
declare module 'babel-preset-gatsby/optimize-hook-destructuring.js' {
  declare module.exports: $Exports<'babel-preset-gatsby/optimize-hook-destructuring'>;
}
