// flow-typed signature: e300b0ba913a182873dfc0eec17ae34c
// flow-typed version: <<STUB>>/eslint-watch_v7.0.0/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-watch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-watch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-watch/build/cli/options' {
  declare module.exports: any;
}

declare module 'eslint-watch/build/commands/clear' {
  declare module.exports: any;
}

declare module 'eslint-watch/build/commands' {
  declare module.exports: any;
}

declare module 'eslint-watch/build/commands/version' {
  declare module.exports: any;
}

declare module 'eslint-watch/build/commands/versions' {
  declare module.exports: any;
}

declare module 'eslint-watch/build/eslint' {
  declare module.exports: any;
}

declare module 'eslint-watch/build/eslint/parser' {
  declare module.exports: any;
}

declare module 'eslint-watch/build/events/watch/chokidar' {
  declare module.exports: any;
}

declare module 'eslint-watch/build/events/watch' {
  declare module.exports: any;
}

declare module 'eslint-watch/build/events/watch/key-listener' {
  declare module.exports: any;
}

declare module 'eslint-watch/build' {
  declare module.exports: any;
}

declare module 'eslint-watch/build/logger' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-watch/build/cli/options.js' {
  declare module.exports: $Exports<'eslint-watch/build/cli/options'>;
}
declare module 'eslint-watch/build/commands/clear.js' {
  declare module.exports: $Exports<'eslint-watch/build/commands/clear'>;
}
declare module 'eslint-watch/build/commands/index' {
  declare module.exports: $Exports<'eslint-watch/build/commands'>;
}
declare module 'eslint-watch/build/commands/index.js' {
  declare module.exports: $Exports<'eslint-watch/build/commands'>;
}
declare module 'eslint-watch/build/commands/version.js' {
  declare module.exports: $Exports<'eslint-watch/build/commands/version'>;
}
declare module 'eslint-watch/build/commands/versions.js' {
  declare module.exports: $Exports<'eslint-watch/build/commands/versions'>;
}
declare module 'eslint-watch/build/eslint/index' {
  declare module.exports: $Exports<'eslint-watch/build/eslint'>;
}
declare module 'eslint-watch/build/eslint/index.js' {
  declare module.exports: $Exports<'eslint-watch/build/eslint'>;
}
declare module 'eslint-watch/build/eslint/parser.js' {
  declare module.exports: $Exports<'eslint-watch/build/eslint/parser'>;
}
declare module 'eslint-watch/build/events/watch/chokidar.js' {
  declare module.exports: $Exports<'eslint-watch/build/events/watch/chokidar'>;
}
declare module 'eslint-watch/build/events/watch/index' {
  declare module.exports: $Exports<'eslint-watch/build/events/watch'>;
}
declare module 'eslint-watch/build/events/watch/index.js' {
  declare module.exports: $Exports<'eslint-watch/build/events/watch'>;
}
declare module 'eslint-watch/build/events/watch/key-listener.js' {
  declare module.exports: $Exports<'eslint-watch/build/events/watch/key-listener'>;
}
declare module 'eslint-watch/build/index' {
  declare module.exports: $Exports<'eslint-watch/build'>;
}
declare module 'eslint-watch/build/index.js' {
  declare module.exports: $Exports<'eslint-watch/build'>;
}
declare module 'eslint-watch/build/logger.js' {
  declare module.exports: $Exports<'eslint-watch/build/logger'>;
}
