// flow-typed signature: 8dce73332b722d01043d1b2c3120c0d2
// flow-typed version: <<STUB>>/gatsby-link_v^2.4.13/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-link'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-link' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-link/parse-path' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-link/index' {
  declare module.exports: $Exports<'gatsby-link'>;
}
declare module 'gatsby-link/index.js' {
  declare module.exports: $Exports<'gatsby-link'>;
}
declare module 'gatsby-link/parse-path.js' {
  declare module.exports: $Exports<'gatsby-link/parse-path'>;
}
