// flow-typed signature: 8d817d2ad98ae641bebc81fc53f4048f
// flow-typed version: <<STUB>>/gatsby-plugin-optimize-svgs_v^1.0.4/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-optimize-svgs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-optimize-svgs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-optimize-svgs/gatsby-node' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-optimize-svgs/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-plugin-optimize-svgs/gatsby-node'>;
}
declare module 'gatsby-plugin-optimize-svgs/index' {
  declare module.exports: $Exports<'gatsby-plugin-optimize-svgs'>;
}
declare module 'gatsby-plugin-optimize-svgs/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-optimize-svgs'>;
}
