// flow-typed signature: 4a1bf2e8ba8afdb2592132943f675401
// flow-typed version: <<STUB>>/gatsby-plugin-google-gtag_v^2.1.10/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-google-gtag'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-google-gtag' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-google-gtag/gatsby-browser' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-google-gtag/gatsby-ssr' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-google-gtag/gatsby-browser.js' {
  declare module.exports: $Exports<'gatsby-plugin-google-gtag/gatsby-browser'>;
}
declare module 'gatsby-plugin-google-gtag/gatsby-ssr.js' {
  declare module.exports: $Exports<'gatsby-plugin-google-gtag/gatsby-ssr'>;
}
declare module 'gatsby-plugin-google-gtag/index' {
  declare module.exports: $Exports<'gatsby-plugin-google-gtag'>;
}
declare module 'gatsby-plugin-google-gtag/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-google-gtag'>;
}
