// flow-typed signature: 6bd6ecc774d3678c3b04f61c6ab9ac2a
// flow-typed version: <<STUB>>/gatsby-remark-relative-images_v^0.3.0/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-remark-relative-images'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-remark-relative-images' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gatsby-remark-relative-images/index' {
  declare module.exports: $Exports<'gatsby-remark-relative-images'>;
}
declare module 'gatsby-remark-relative-images/index.js' {
  declare module.exports: $Exports<'gatsby-remark-relative-images'>;
}
