// flow-typed signature: 7d0790c3fda54530c845b2d708546e2d
// flow-typed version: <<STUB>>/gatsby-remark-katex_v^3.3.10/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-remark-katex'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-remark-katex' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-remark-katex/src/__tests__' {
  declare module.exports: any;
}

declare module 'gatsby-remark-katex/src' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-remark-katex/index' {
  declare module.exports: $Exports<'gatsby-remark-katex'>;
}
declare module 'gatsby-remark-katex/index.js' {
  declare module.exports: $Exports<'gatsby-remark-katex'>;
}
declare module 'gatsby-remark-katex/src/__tests__/index' {
  declare module.exports: $Exports<'gatsby-remark-katex/src/__tests__'>;
}
declare module 'gatsby-remark-katex/src/__tests__/index.js' {
  declare module.exports: $Exports<'gatsby-remark-katex/src/__tests__'>;
}
declare module 'gatsby-remark-katex/src/index' {
  declare module.exports: $Exports<'gatsby-remark-katex/src'>;
}
declare module 'gatsby-remark-katex/src/index.js' {
  declare module.exports: $Exports<'gatsby-remark-katex/src'>;
}
