// flow-typed signature: 76fcda058c472ced13d73fa3d28257d6
// flow-typed version: <<STUB>>/gatsby-remark-embed-youtube_v^0.0.7/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-remark-embed-youtube'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-remark-embed-youtube' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gatsby-remark-embed-youtube/index' {
  declare module.exports: $Exports<'gatsby-remark-embed-youtube'>;
}
declare module 'gatsby-remark-embed-youtube/index.js' {
  declare module.exports: $Exports<'gatsby-remark-embed-youtube'>;
}
