// flow-typed signature: 14fbdf6eac340dac06af27b7d3d4eca9
// flow-typed version: <<STUB>>/katex_v^0.12.0/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'katex'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'katex' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'katex/cli' {
  declare module.exports: any;
}

declare module 'katex/contrib/auto-render/auto-render' {
  declare module.exports: any;
}

declare module 'katex/contrib/auto-render/splitAtDelimiters' {
  declare module.exports: any;
}

declare module 'katex/contrib/auto-render/test/auto-render-spec' {
  declare module.exports: any;
}

declare module 'katex/contrib/copy-tex/copy-tex' {
  declare module.exports: any;
}

declare module 'katex/contrib/copy-tex/copy-tex.webpack' {
  declare module.exports: any;
}

declare module 'katex/contrib/copy-tex/katex2tex' {
  declare module.exports: any;
}

declare module 'katex/contrib/mathtex-script-type/mathtex-script-type' {
  declare module.exports: any;
}

declare module 'katex/contrib/mhchem/mhchem' {
  declare module.exports: any;
}

declare module 'katex/contrib/render-a11y-string/render-a11y-string' {
  declare module.exports: any;
}

declare module 'katex/contrib/render-a11y-string/test/render-a11y-string-spec' {
  declare module.exports: any;
}

declare module 'katex/dist/contrib/auto-render' {
  declare module.exports: any;
}

declare module 'katex/dist/contrib/auto-render.min' {
  declare module.exports: any;
}

declare module 'katex/dist/contrib/copy-tex' {
  declare module.exports: any;
}

declare module 'katex/dist/contrib/copy-tex.min' {
  declare module.exports: any;
}

declare module 'katex/dist/contrib/mathtex-script-type' {
  declare module.exports: any;
}

declare module 'katex/dist/contrib/mathtex-script-type.min' {
  declare module.exports: any;
}

declare module 'katex/dist/contrib/mhchem' {
  declare module.exports: any;
}

declare module 'katex/dist/contrib/mhchem.min' {
  declare module.exports: any;
}

declare module 'katex/dist/contrib/render-a11y-string' {
  declare module.exports: any;
}

declare module 'katex/dist/contrib/render-a11y-string.min' {
  declare module.exports: any;
}

declare module 'katex/dist/katex' {
  declare module.exports: any;
}

declare module 'katex/dist/katex.min' {
  declare module.exports: any;
}

declare module 'katex/katex' {
  declare module.exports: any;
}

declare module 'katex/src/buildCommon' {
  declare module.exports: any;
}

declare module 'katex/src/buildHTML' {
  declare module.exports: any;
}

declare module 'katex/src/buildMathML' {
  declare module.exports: any;
}

declare module 'katex/src/buildTree' {
  declare module.exports: any;
}

declare module 'katex/src/defineEnvironment' {
  declare module.exports: any;
}

declare module 'katex/src/defineFunction' {
  declare module.exports: any;
}

declare module 'katex/src/delimiter' {
  declare module.exports: any;
}

declare module 'katex/src/domTree' {
  declare module.exports: any;
}

declare module 'katex/src/environments' {
  declare module.exports: any;
}

declare module 'katex/src/environments/array' {
  declare module.exports: any;
}

declare module 'katex/src/fontMetrics' {
  declare module.exports: any;
}

declare module 'katex/src/functions' {
  declare module.exports: any;
}

declare module 'katex/src/functions/accent' {
  declare module.exports: any;
}

declare module 'katex/src/functions/accentunder' {
  declare module.exports: any;
}

declare module 'katex/src/functions/arrow' {
  declare module.exports: any;
}

declare module 'katex/src/functions/char' {
  declare module.exports: any;
}

declare module 'katex/src/functions/color' {
  declare module.exports: any;
}

declare module 'katex/src/functions/cr' {
  declare module.exports: any;
}

declare module 'katex/src/functions/def' {
  declare module.exports: any;
}

declare module 'katex/src/functions/delimsizing' {
  declare module.exports: any;
}

declare module 'katex/src/functions/enclose' {
  declare module.exports: any;
}

declare module 'katex/src/functions/environment' {
  declare module.exports: any;
}

declare module 'katex/src/functions/font' {
  declare module.exports: any;
}

declare module 'katex/src/functions/genfrac' {
  declare module.exports: any;
}

declare module 'katex/src/functions/horizBrace' {
  declare module.exports: any;
}

declare module 'katex/src/functions/href' {
  declare module.exports: any;
}

declare module 'katex/src/functions/html' {
  declare module.exports: any;
}

declare module 'katex/src/functions/htmlmathml' {
  declare module.exports: any;
}

declare module 'katex/src/functions/includegraphics' {
  declare module.exports: any;
}

declare module 'katex/src/functions/kern' {
  declare module.exports: any;
}

declare module 'katex/src/functions/lap' {
  declare module.exports: any;
}

declare module 'katex/src/functions/math' {
  declare module.exports: any;
}

declare module 'katex/src/functions/mathchoice' {
  declare module.exports: any;
}

declare module 'katex/src/functions/mclass' {
  declare module.exports: any;
}

declare module 'katex/src/functions/op' {
  declare module.exports: any;
}

declare module 'katex/src/functions/operatorname' {
  declare module.exports: any;
}

declare module 'katex/src/functions/ordgroup' {
  declare module.exports: any;
}

declare module 'katex/src/functions/overline' {
  declare module.exports: any;
}

declare module 'katex/src/functions/phantom' {
  declare module.exports: any;
}

declare module 'katex/src/functions/raisebox' {
  declare module.exports: any;
}

declare module 'katex/src/functions/rule' {
  declare module.exports: any;
}

declare module 'katex/src/functions/sizing' {
  declare module.exports: any;
}

declare module 'katex/src/functions/smash' {
  declare module.exports: any;
}

declare module 'katex/src/functions/sqrt' {
  declare module.exports: any;
}

declare module 'katex/src/functions/styling' {
  declare module.exports: any;
}

declare module 'katex/src/functions/supsub' {
  declare module.exports: any;
}

declare module 'katex/src/functions/symbolsOp' {
  declare module.exports: any;
}

declare module 'katex/src/functions/symbolsOrd' {
  declare module.exports: any;
}

declare module 'katex/src/functions/symbolsSpacing' {
  declare module.exports: any;
}

declare module 'katex/src/functions/tag' {
  declare module.exports: any;
}

declare module 'katex/src/functions/text' {
  declare module.exports: any;
}

declare module 'katex/src/functions/underline' {
  declare module.exports: any;
}

declare module 'katex/src/functions/utils/assembleSupSub' {
  declare module.exports: any;
}

declare module 'katex/src/functions/verb' {
  declare module.exports: any;
}

declare module 'katex/src/Lexer' {
  declare module.exports: any;
}

declare module 'katex/src/MacroExpander' {
  declare module.exports: any;
}

declare module 'katex/src/macros' {
  declare module.exports: any;
}

declare module 'katex/src/mathMLTree' {
  declare module.exports: any;
}

declare module 'katex/src/Namespace' {
  declare module.exports: any;
}

declare module 'katex/src/Options' {
  declare module.exports: any;
}

declare module 'katex/src/ParseError' {
  declare module.exports: any;
}

declare module 'katex/src/parseNode' {
  declare module.exports: any;
}

declare module 'katex/src/Parser' {
  declare module.exports: any;
}

declare module 'katex/src/parseTree' {
  declare module.exports: any;
}

declare module 'katex/src/Settings' {
  declare module.exports: any;
}

declare module 'katex/src/SourceLocation' {
  declare module.exports: any;
}

declare module 'katex/src/spacingData' {
  declare module.exports: any;
}

declare module 'katex/src/stretchy' {
  declare module.exports: any;
}

declare module 'katex/src/Style' {
  declare module.exports: any;
}

declare module 'katex/src/svgGeometry' {
  declare module.exports: any;
}

declare module 'katex/src/symbols' {
  declare module.exports: any;
}

declare module 'katex/src/Token' {
  declare module.exports: any;
}

declare module 'katex/src/tree' {
  declare module.exports: any;
}

declare module 'katex/src/types' {
  declare module.exports: any;
}

declare module 'katex/src/unicodeAccents' {
  declare module.exports: any;
}

declare module 'katex/src/unicodeScripts' {
  declare module.exports: any;
}

declare module 'katex/src/unicodeSymbols' {
  declare module.exports: any;
}

declare module 'katex/src/units' {
  declare module.exports: any;
}

declare module 'katex/src/utils' {
  declare module.exports: any;
}

declare module 'katex/src/wide-character' {
  declare module.exports: any;
}

// Filename aliases
declare module 'katex/cli.js' {
  declare module.exports: $Exports<'katex/cli'>;
}
declare module 'katex/contrib/auto-render/auto-render.js' {
  declare module.exports: $Exports<'katex/contrib/auto-render/auto-render'>;
}
declare module 'katex/contrib/auto-render/splitAtDelimiters.js' {
  declare module.exports: $Exports<'katex/contrib/auto-render/splitAtDelimiters'>;
}
declare module 'katex/contrib/auto-render/test/auto-render-spec.js' {
  declare module.exports: $Exports<'katex/contrib/auto-render/test/auto-render-spec'>;
}
declare module 'katex/contrib/copy-tex/copy-tex.js' {
  declare module.exports: $Exports<'katex/contrib/copy-tex/copy-tex'>;
}
declare module 'katex/contrib/copy-tex/copy-tex.webpack.js' {
  declare module.exports: $Exports<'katex/contrib/copy-tex/copy-tex.webpack'>;
}
declare module 'katex/contrib/copy-tex/katex2tex.js' {
  declare module.exports: $Exports<'katex/contrib/copy-tex/katex2tex'>;
}
declare module 'katex/contrib/mathtex-script-type/mathtex-script-type.js' {
  declare module.exports: $Exports<'katex/contrib/mathtex-script-type/mathtex-script-type'>;
}
declare module 'katex/contrib/mhchem/mhchem.js' {
  declare module.exports: $Exports<'katex/contrib/mhchem/mhchem'>;
}
declare module 'katex/contrib/render-a11y-string/render-a11y-string.js' {
  declare module.exports: $Exports<'katex/contrib/render-a11y-string/render-a11y-string'>;
}
declare module 'katex/contrib/render-a11y-string/test/render-a11y-string-spec.js' {
  declare module.exports: $Exports<'katex/contrib/render-a11y-string/test/render-a11y-string-spec'>;
}
declare module 'katex/dist/contrib/auto-render.js' {
  declare module.exports: $Exports<'katex/dist/contrib/auto-render'>;
}
declare module 'katex/dist/contrib/auto-render.min.js' {
  declare module.exports: $Exports<'katex/dist/contrib/auto-render.min'>;
}
declare module 'katex/dist/contrib/copy-tex.js' {
  declare module.exports: $Exports<'katex/dist/contrib/copy-tex'>;
}
declare module 'katex/dist/contrib/copy-tex.min.js' {
  declare module.exports: $Exports<'katex/dist/contrib/copy-tex.min'>;
}
declare module 'katex/dist/contrib/mathtex-script-type.js' {
  declare module.exports: $Exports<'katex/dist/contrib/mathtex-script-type'>;
}
declare module 'katex/dist/contrib/mathtex-script-type.min.js' {
  declare module.exports: $Exports<'katex/dist/contrib/mathtex-script-type.min'>;
}
declare module 'katex/dist/contrib/mhchem.js' {
  declare module.exports: $Exports<'katex/dist/contrib/mhchem'>;
}
declare module 'katex/dist/contrib/mhchem.min.js' {
  declare module.exports: $Exports<'katex/dist/contrib/mhchem.min'>;
}
declare module 'katex/dist/contrib/render-a11y-string.js' {
  declare module.exports: $Exports<'katex/dist/contrib/render-a11y-string'>;
}
declare module 'katex/dist/contrib/render-a11y-string.min.js' {
  declare module.exports: $Exports<'katex/dist/contrib/render-a11y-string.min'>;
}
declare module 'katex/dist/katex.js' {
  declare module.exports: $Exports<'katex/dist/katex'>;
}
declare module 'katex/dist/katex.min.js' {
  declare module.exports: $Exports<'katex/dist/katex.min'>;
}
declare module 'katex/katex.js' {
  declare module.exports: $Exports<'katex/katex'>;
}
declare module 'katex/src/buildCommon.js' {
  declare module.exports: $Exports<'katex/src/buildCommon'>;
}
declare module 'katex/src/buildHTML.js' {
  declare module.exports: $Exports<'katex/src/buildHTML'>;
}
declare module 'katex/src/buildMathML.js' {
  declare module.exports: $Exports<'katex/src/buildMathML'>;
}
declare module 'katex/src/buildTree.js' {
  declare module.exports: $Exports<'katex/src/buildTree'>;
}
declare module 'katex/src/defineEnvironment.js' {
  declare module.exports: $Exports<'katex/src/defineEnvironment'>;
}
declare module 'katex/src/defineFunction.js' {
  declare module.exports: $Exports<'katex/src/defineFunction'>;
}
declare module 'katex/src/delimiter.js' {
  declare module.exports: $Exports<'katex/src/delimiter'>;
}
declare module 'katex/src/domTree.js' {
  declare module.exports: $Exports<'katex/src/domTree'>;
}
declare module 'katex/src/environments.js' {
  declare module.exports: $Exports<'katex/src/environments'>;
}
declare module 'katex/src/environments/array.js' {
  declare module.exports: $Exports<'katex/src/environments/array'>;
}
declare module 'katex/src/fontMetrics.js' {
  declare module.exports: $Exports<'katex/src/fontMetrics'>;
}
declare module 'katex/src/functions.js' {
  declare module.exports: $Exports<'katex/src/functions'>;
}
declare module 'katex/src/functions/accent.js' {
  declare module.exports: $Exports<'katex/src/functions/accent'>;
}
declare module 'katex/src/functions/accentunder.js' {
  declare module.exports: $Exports<'katex/src/functions/accentunder'>;
}
declare module 'katex/src/functions/arrow.js' {
  declare module.exports: $Exports<'katex/src/functions/arrow'>;
}
declare module 'katex/src/functions/char.js' {
  declare module.exports: $Exports<'katex/src/functions/char'>;
}
declare module 'katex/src/functions/color.js' {
  declare module.exports: $Exports<'katex/src/functions/color'>;
}
declare module 'katex/src/functions/cr.js' {
  declare module.exports: $Exports<'katex/src/functions/cr'>;
}
declare module 'katex/src/functions/def.js' {
  declare module.exports: $Exports<'katex/src/functions/def'>;
}
declare module 'katex/src/functions/delimsizing.js' {
  declare module.exports: $Exports<'katex/src/functions/delimsizing'>;
}
declare module 'katex/src/functions/enclose.js' {
  declare module.exports: $Exports<'katex/src/functions/enclose'>;
}
declare module 'katex/src/functions/environment.js' {
  declare module.exports: $Exports<'katex/src/functions/environment'>;
}
declare module 'katex/src/functions/font.js' {
  declare module.exports: $Exports<'katex/src/functions/font'>;
}
declare module 'katex/src/functions/genfrac.js' {
  declare module.exports: $Exports<'katex/src/functions/genfrac'>;
}
declare module 'katex/src/functions/horizBrace.js' {
  declare module.exports: $Exports<'katex/src/functions/horizBrace'>;
}
declare module 'katex/src/functions/href.js' {
  declare module.exports: $Exports<'katex/src/functions/href'>;
}
declare module 'katex/src/functions/html.js' {
  declare module.exports: $Exports<'katex/src/functions/html'>;
}
declare module 'katex/src/functions/htmlmathml.js' {
  declare module.exports: $Exports<'katex/src/functions/htmlmathml'>;
}
declare module 'katex/src/functions/includegraphics.js' {
  declare module.exports: $Exports<'katex/src/functions/includegraphics'>;
}
declare module 'katex/src/functions/kern.js' {
  declare module.exports: $Exports<'katex/src/functions/kern'>;
}
declare module 'katex/src/functions/lap.js' {
  declare module.exports: $Exports<'katex/src/functions/lap'>;
}
declare module 'katex/src/functions/math.js' {
  declare module.exports: $Exports<'katex/src/functions/math'>;
}
declare module 'katex/src/functions/mathchoice.js' {
  declare module.exports: $Exports<'katex/src/functions/mathchoice'>;
}
declare module 'katex/src/functions/mclass.js' {
  declare module.exports: $Exports<'katex/src/functions/mclass'>;
}
declare module 'katex/src/functions/op.js' {
  declare module.exports: $Exports<'katex/src/functions/op'>;
}
declare module 'katex/src/functions/operatorname.js' {
  declare module.exports: $Exports<'katex/src/functions/operatorname'>;
}
declare module 'katex/src/functions/ordgroup.js' {
  declare module.exports: $Exports<'katex/src/functions/ordgroup'>;
}
declare module 'katex/src/functions/overline.js' {
  declare module.exports: $Exports<'katex/src/functions/overline'>;
}
declare module 'katex/src/functions/phantom.js' {
  declare module.exports: $Exports<'katex/src/functions/phantom'>;
}
declare module 'katex/src/functions/raisebox.js' {
  declare module.exports: $Exports<'katex/src/functions/raisebox'>;
}
declare module 'katex/src/functions/rule.js' {
  declare module.exports: $Exports<'katex/src/functions/rule'>;
}
declare module 'katex/src/functions/sizing.js' {
  declare module.exports: $Exports<'katex/src/functions/sizing'>;
}
declare module 'katex/src/functions/smash.js' {
  declare module.exports: $Exports<'katex/src/functions/smash'>;
}
declare module 'katex/src/functions/sqrt.js' {
  declare module.exports: $Exports<'katex/src/functions/sqrt'>;
}
declare module 'katex/src/functions/styling.js' {
  declare module.exports: $Exports<'katex/src/functions/styling'>;
}
declare module 'katex/src/functions/supsub.js' {
  declare module.exports: $Exports<'katex/src/functions/supsub'>;
}
declare module 'katex/src/functions/symbolsOp.js' {
  declare module.exports: $Exports<'katex/src/functions/symbolsOp'>;
}
declare module 'katex/src/functions/symbolsOrd.js' {
  declare module.exports: $Exports<'katex/src/functions/symbolsOrd'>;
}
declare module 'katex/src/functions/symbolsSpacing.js' {
  declare module.exports: $Exports<'katex/src/functions/symbolsSpacing'>;
}
declare module 'katex/src/functions/tag.js' {
  declare module.exports: $Exports<'katex/src/functions/tag'>;
}
declare module 'katex/src/functions/text.js' {
  declare module.exports: $Exports<'katex/src/functions/text'>;
}
declare module 'katex/src/functions/underline.js' {
  declare module.exports: $Exports<'katex/src/functions/underline'>;
}
declare module 'katex/src/functions/utils/assembleSupSub.js' {
  declare module.exports: $Exports<'katex/src/functions/utils/assembleSupSub'>;
}
declare module 'katex/src/functions/verb.js' {
  declare module.exports: $Exports<'katex/src/functions/verb'>;
}
declare module 'katex/src/Lexer.js' {
  declare module.exports: $Exports<'katex/src/Lexer'>;
}
declare module 'katex/src/MacroExpander.js' {
  declare module.exports: $Exports<'katex/src/MacroExpander'>;
}
declare module 'katex/src/macros.js' {
  declare module.exports: $Exports<'katex/src/macros'>;
}
declare module 'katex/src/mathMLTree.js' {
  declare module.exports: $Exports<'katex/src/mathMLTree'>;
}
declare module 'katex/src/Namespace.js' {
  declare module.exports: $Exports<'katex/src/Namespace'>;
}
declare module 'katex/src/Options.js' {
  declare module.exports: $Exports<'katex/src/Options'>;
}
declare module 'katex/src/ParseError.js' {
  declare module.exports: $Exports<'katex/src/ParseError'>;
}
declare module 'katex/src/parseNode.js' {
  declare module.exports: $Exports<'katex/src/parseNode'>;
}
declare module 'katex/src/Parser.js' {
  declare module.exports: $Exports<'katex/src/Parser'>;
}
declare module 'katex/src/parseTree.js' {
  declare module.exports: $Exports<'katex/src/parseTree'>;
}
declare module 'katex/src/Settings.js' {
  declare module.exports: $Exports<'katex/src/Settings'>;
}
declare module 'katex/src/SourceLocation.js' {
  declare module.exports: $Exports<'katex/src/SourceLocation'>;
}
declare module 'katex/src/spacingData.js' {
  declare module.exports: $Exports<'katex/src/spacingData'>;
}
declare module 'katex/src/stretchy.js' {
  declare module.exports: $Exports<'katex/src/stretchy'>;
}
declare module 'katex/src/Style.js' {
  declare module.exports: $Exports<'katex/src/Style'>;
}
declare module 'katex/src/svgGeometry.js' {
  declare module.exports: $Exports<'katex/src/svgGeometry'>;
}
declare module 'katex/src/symbols.js' {
  declare module.exports: $Exports<'katex/src/symbols'>;
}
declare module 'katex/src/Token.js' {
  declare module.exports: $Exports<'katex/src/Token'>;
}
declare module 'katex/src/tree.js' {
  declare module.exports: $Exports<'katex/src/tree'>;
}
declare module 'katex/src/types.js' {
  declare module.exports: $Exports<'katex/src/types'>;
}
declare module 'katex/src/unicodeAccents.js' {
  declare module.exports: $Exports<'katex/src/unicodeAccents'>;
}
declare module 'katex/src/unicodeScripts.js' {
  declare module.exports: $Exports<'katex/src/unicodeScripts'>;
}
declare module 'katex/src/unicodeSymbols.js' {
  declare module.exports: $Exports<'katex/src/unicodeSymbols'>;
}
declare module 'katex/src/units.js' {
  declare module.exports: $Exports<'katex/src/units'>;
}
declare module 'katex/src/utils.js' {
  declare module.exports: $Exports<'katex/src/utils'>;
}
declare module 'katex/src/wide-character.js' {
  declare module.exports: $Exports<'katex/src/wide-character'>;
}
